//
// Created by ilya on 22.11.2019.
//

#ifndef YANDEXCPLUSPLUS_4_BROWN_5_WEEK_9_TASK_BUDGET_TEST_H_
#define YANDEXCPLUSPLUS_4_BROWN_5_WEEK_9_TASK_BUDGET_TEST_H_

void TestCreateDate();
void TestDiffDate();

#endif //YANDEXCPLUSPLUS_4_BROWN_5_WEEK_9_TASK_BUDGET_TEST_H_
