//
// Created by ilya on 25.11.2019.
//

#ifndef YANDEXCPLUSPLUS_4_BROWN_FINAL_PROJECT_PART_A_REQUEST_H
#define YANDEXCPLUSPLUS_4_BROWN_FINAL_PROJECT_PART_A_REQUEST_H

class Request {

};

#endif //YANDEXYELLOWFINAL_4_BROWN_FINAL_PROJECT_PART_A_REQUEST_H
